#!/bin/python
import requests
from bs4 import BeautifulSoup

youtubers = ["@penguinz", "@watsonamelia"]

base_url = "https://www.youtube.com/"
live = "/live/"

def check(url):
    html = requests.get(url).text
    soup = BeautifulSoup(html, "lxml")
    results = soup.find_all("link", rel="canonical")

    name = url.split("/")[3] + ": "
    if "channel" in results[0].get('href'):
        return name + "\033[31m●\033[0m"
    return name + "\033[32m●\033[0"

if __name__ == "__main__":
    for youtuber in youtubers:
        print(check(base_url + youtuber + live))
